apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderprocessingservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orderprocessingservice
  template:
    metadata:
      labels:
        app: orderprocessingservice
    spec:
      containers:
        - name: orderprocessingservice
          image: stwomack/orderprocessingservice:latest
          ports:
            - containerPort: 8080