apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: orderprocessingservice-image
  namespace: default
spec:
  tag: stwomack/orderprocessingservice
  serviceAccountName: main-builder-service-account
  builder:
    name: main-builder
    kind: Builder
  source:
    git:
      url: https://github.com/stwomack/orderprocessingservice
      revision: main