apiVersion: v1
kind: Service
metadata:
  name: orderprocessing-service
spec:
  type: LoadBalancer
  selector:
    app: orderprocessingservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080